/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
//actulz

import Entidades.Alumno;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import persistencia.AlumnoData;

/**
 *
 * @author jimes
 */
public class FrAlumno extends javax.swing.JInternalFrame {

    AlumnoData al;

    /**
     * Creates new form FrAlumno
     */
    public FrAlumno() {
        initComponents();
        this.al = new AlumnoData();
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BxBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BxEstado = new javax.swing.JCheckBox();
        TxApellido = new javax.swing.JTextField();
        TxNombre = new javax.swing.JTextField();
        BxGuardar = new javax.swing.JButton();
        BxBorrar = new javax.swing.JButton();
        BxActualizar = new javax.swing.JButton();
        BxLimpiar = new javax.swing.JButton();
        TxLegajo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxDNI = new javax.swing.JTextField();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        BxSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Alta - Baja - Modificación Alumno");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Legajo");

        BxBuscar.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        BxBuscar.setForeground(new java.awt.Color(51, 0, 255));
        BxBuscar.setText("Buscar");
        BxBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        jLabel4.setText("Nombre");

        jLabel5.setText("Fecha Nac");

        BxEstado.setSelected(true);
        BxEstado.setText("Activo");
        BxEstado.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BxEstado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BxEstado.setIconTextGap(20);
        BxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxEstadoActionPerformed(evt);
            }
        });

        TxApellido.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TxApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxApellidoActionPerformed(evt);
            }
        });

        TxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxNombreActionPerformed(evt);
            }
        });

        BxGuardar.setText("Guardar");
        BxGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxGuardarActionPerformed(evt);
            }
        });

        BxBorrar.setText("Borrar");
        BxBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxBorrarActionPerformed(evt);
            }
        });

        BxActualizar.setText("Actualizar");
        BxActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxActualizarActionPerformed(evt);
            }
        });

        BxLimpiar.setText("Limpiar");
        BxLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxLimpiarActionPerformed(evt);
            }
        });

        TxLegajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxLegajoFocusLost(evt);
            }
        });
        TxLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxLegajoActionPerformed(evt);
            }
        });

        jLabel6.setText("DNI");

        TxDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxDNIFocusLost(evt);
            }
        });
        TxDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDNIActionPerformed(evt);
            }
        });

        BxSalir.setText("SALIR");
        BxSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BxSalirActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mar.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(TxNombre)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 151, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BxEstado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BxGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BxBorrar)
                                .addGap(18, 18, 18)
                                .addComponent(BxActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BxLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BxSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(203, 203, 203)
                                        .addComponent(BxBuscar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BxBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BxEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BxGuardar)
                            .addComponent(BxBorrar)
                            .addComponent(BxActualizar)
                            .addComponent(BxLimpiar)
                            .addComponent(BxSalir)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxBuscarActionPerformed

        if (this.TxLegajo.getText().matches("[+-]?\\d*(\\.\\d+)?")) {
            if (this.TxLegajo.getText().equals("")) {
                this.TxLegajo.setText("0");
            }
            Alumno alumno = al.buscarAlumno(Integer.parseInt(this.TxLegajo.getText()));
            this.TxApellido.setText(alumno.getApellido());
            this.TxNombre.setText(alumno.getNombre());
            this.TxDNI.setText(String.valueOf(alumno.getDni()));
            LocalDate lc = alumno.getFecha_nacimiento();
            if (alumno.getFecha_nacimiento() != null) {
                java.util.Date date = Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
                jDateFechaNacimiento.setDate(date);
            }

            this.BxEstado.setSelected(alumno.getEstado());
        }

    }//GEN-LAST:event_BxBuscarActionPerformed

    private void BxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BxEstadoActionPerformed

    private void TxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxNombreActionPerformed

    private void BxGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxGuardarActionPerformed
        Alumno alu = new Alumno();
        alu.setApellido(TxApellido.getText());
        alu.setNombre(TxNombre.getText());
        alu.setDni(Long.parseLong(TxDNI.getText()));
        alu.setEstado(BxEstado.isSelected());
        alu.setFecha_nacimiento(LocalDate.parse(new SimpleDateFormat("yyyy-MM-dd").format(jDateFechaNacimiento.getDate())));
        al.guardarAlumno(alu);
        TxLegajo.setText(alu.getId_alumno() + "");
        // Alumno alumno = new Alumno(this.TxDNI.getText(),this.TxApellido.getText(),this.TxNombre.getText(),this.TxFechaDeNacimiento.getText(),this.BxEstado.action(true, ui)); 

        // this.al.guardarAlumno(alumno);// TODO add your handling code here:
    }//GEN-LAST:event_BxGuardarActionPerformed

    private void TxApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxApellidoActionPerformed

    private void TxLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxLegajoActionPerformed


    }//GEN-LAST:event_TxLegajoActionPerformed

    private void BxBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxBorrarActionPerformed

        al.borrarAlumno(Integer.parseInt(this.TxLegajo.getText()));

        JOptionPane.showMessageDialog(this, "El alumuno fue borrado");
        limpiarCampo();


    }//GEN-LAST:event_BxBorrarActionPerformed

    private void BxLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxLimpiarActionPerformed
        limpiarCampo();
    }//GEN-LAST:event_BxLimpiarActionPerformed

    private void BxActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxActualizarActionPerformed
        Alumno alumno = al.buscarAlumno(Integer.parseInt(this.TxLegajo.getText()));

        alumno.setApellido(this.TxApellido.getText());
        alumno.setApellido(this.TxApellido.getText());
        alumno.setNombre(this.TxNombre.getText());
        alumno.setDni(Integer.parseInt(this.TxDNI.getText()));
        alumno.setFecha_nacimiento(LocalDate.parse(new SimpleDateFormat("yyyy-MM-dd").format(jDateFechaNacimiento.getDate())));
        al.actualizarAlumno(alumno);
    }//GEN-LAST:event_BxActualizarActionPerformed

    private void TxLegajoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxLegajoFocusLost
        if (!this.TxLegajo.getText().matches("[+-]?\\d*(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero");
            this.TxLegajo.requestFocus();
        }
    }//GEN-LAST:event_TxLegajoFocusLost

    private void TxDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxDNIFocusLost
        if (!this.TxDNI.getText().matches("[+-]?\\d*(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero");
            this.TxDNI.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "el numero de dni no debe contener espacios ni puntos");
        }
    }//GEN-LAST:event_TxDNIFocusLost

    private void TxDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDNIActionPerformed

    private void BxSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BxSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BxSalirActionPerformed
    private void limpiarCampo() {

        this.TxApellido.setText("");
        this.TxNombre.setText("");
        this.TxDNI.setText("");
        this.TxLegajo.setText("");
        //this.jDateFechaNacimiento();
        this.BxEstado.setSelected(false);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BxActualizar;
    private javax.swing.JButton BxBorrar;
    private javax.swing.JButton BxBuscar;
    private javax.swing.JCheckBox BxEstado;
    private javax.swing.JButton BxGuardar;
    private javax.swing.JButton BxLimpiar;
    private javax.swing.JButton BxSalir;
    private javax.swing.JTextField TxApellido;
    private javax.swing.JTextField TxDNI;
    private javax.swing.JTextField TxLegajo;
    private javax.swing.JTextField TxNombre;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JTextField tIdMateria;
    // End of variables declaration//GEN-END:variables
}
